# Generated by Django 5.2.3 on 2025-07-01 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fichier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('fichier', models.FileField(upload_to='uploads/')),
                ('observation', models.TextField(blank=True)),
                ('date_televersement', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PredictionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.IntegerField()),
                ('taux_change', models.FloatField()),
                ('masse_monnaire', models.FloatField()),
                ('inflation_reelle', models.FloatField(blank=True, null=True)),
                ('inflation_predite', models.FloatField(blank=True, null=True)),
                ('date_prediction', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
